import { Head, useForm } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';

const EXAMPLES = [
    'Which 3 projects are the stalest and need attention first?',
    'Which projects have critical findings I should fix today?',
    'Which projects are missing tests or CI?',
    'Summarize the overall health of my portfolio.',
];

export default function AskIndex({ available, question, answer }) {
    const { data, setData, post, processing } = useForm({ question: question ?? '' });

    const submit = (e) => {
        e.preventDefault();
        if (data.question.trim()) post('/ask', { preserveScroll: true });
    };

    return (
        <AppLayout title="Ask AI">
            <Head title="Ask AI" />

            <div className="mx-auto max-w-3xl space-y-6">
                <p className="text-sm text-gray-500">
                    Ask a question about your projects. The answer is generated by your local LLM
                    (Ollama) using the scanned data — stacks, git state, and open findings.
                </p>

                {!available && (
                    <div className="rounded-md bg-amber-50 px-4 py-3 text-sm text-amber-800 ring-1 ring-amber-600/20">
                        Local LLM (Ollama) isn't reachable. Start Ollama and pull the model, then reload.
                    </div>
                )}

                <form onSubmit={submit} className="space-y-3">
                    <textarea
                        value={data.question}
                        onChange={(e) => setData('question', e.target.value)}
                        rows={3}
                        placeholder="e.g. Which projects need the most work?"
                        className="w-full rounded-md border border-gray-300 p-3 text-sm focus:border-indigo-500 focus:ring-indigo-500"
                    />
                    <div className="flex flex-wrap items-center gap-2">
                        <button
                            type="submit"
                            disabled={processing || !available}
                            className="rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-500 disabled:opacity-50"
                        >
                            {processing ? 'Thinking…' : 'Ask'}
                        </button>
                        {EXAMPLES.map((ex) => (
                            <button
                                key={ex}
                                type="button"
                                onClick={() => setData('question', ex)}
                                className="rounded-full border border-gray-200 px-3 py-1 text-xs text-gray-600 hover:bg-gray-50"
                            >
                                {ex}
                            </button>
                        ))}
                    </div>
                </form>

                {answer && (
                    <div className="rounded-lg border border-gray-200 bg-white p-5">
                        {question && (
                            <p className="mb-3 text-sm font-medium text-gray-900">{question}</p>
                        )}
                        <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-gray-700">
                            {answer}
                        </pre>
                    </div>
                )}
            </div>
        </AppLayout>
    );
}
